# Generated by Django 3.1.2 on 2020-10-18 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1)),
                ('department', models.CharField(choices=[('GTO', 'GTO Department'), ('IO', 'IO Department'), ('PSYCH', 'PSYCH Department'), ('PD', 'PD Department'), ('IT', 'Intt Test Department')], default='PSYCH', max_length=5)),
                ('position', models.IntegerField(choices=[(1, 'HOD'), (2, 'COLONEL'), (3, 'BRIG')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Briefcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='document')),
                ('file_name', models.CharField(max_length=128)),
                ('file_type', models.CharField(max_length=48)),
                ('fize_size', models.CharField(max_length=256)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, to='assessor.assessor')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('status', models.IntegerField(choices=[(1, 'Available'), (2, 'Not Available')], default=1)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, to='assessor.assessor')),
            ],
        ),
    ]
