# Generated by Django 3.1.2 on 2020-10-22 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Department Name')),
                ('code', models.CharField(max_length=10, verbose_name='Department Code')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=64, verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='Briefcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='document')),
                ('file_name', models.CharField(max_length=128)),
                ('file_size', models.CharField(default='1', max_length=48)),
                ('file_type', models.IntegerField(choices=[(1, 'Video'), (2, 'Document'), (3, 'Image')], default=2)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, to='assessor.assessor')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('status', models.IntegerField(choices=[(1, 'Available'), (2, 'Not Available')], default=1)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, to='assessor.assessor')),
            ],
        ),
        migrations.AddField(
            model_name='assessor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessor.department'),
        ),
        migrations.AddField(
            model_name='assessor',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessor.position'),
        ),
        migrations.AddField(
            model_name='assessor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
