# Generated by Django 3.1.2 on 2020-10-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='designation',
            field=models.CharField(max_length=64, verbose_name='Designation'),
        ),
    ]
