# Generated by Django 3.1.2 on 2020-11-22 05:33

import assessor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessor', '0002_auto_20201023_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=assessor.models.upload_image, verbose_name='Upload Your Profile Picture'),
        ),
    ]
