# Generated by Django 3.1.2 on 2020-11-22 05:58

import army_backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessor', '0003_assessor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=army_backend.utils.upload_image, verbose_name='Upload Your \nProfile Picture'),
        ),
    ]
