# Generated by Django 3.1.2 on 2020-11-23 18:44

import army_backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessor', '0004_auto_20201122_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefcase',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='briefcase',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='briefcase',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='briefcase',
            name='file_url',
        ),
        migrations.AddField(
            model_name='briefcase',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=army_backend.utils.upload_file, verbose_name='Upload Your File'),
        ),
    ]
