# Generated by Django 3.1.2 on 2020-12-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessor', '0006_auto_20201219_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefcase',
            name='size',
            field=models.IntegerField(default=0, verbose_name='Size in KB'),
        ),
    ]
