# Generated by Django 3.1.2 on 2020-11-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_currentaffair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaffair',
            name='category',
            field=models.CharField(choices=[('1', 'INTERNATIONAL'), ('2', 'NATIONAL'), ('3', 'ECONOMY'), ('4', 'DEFENCE'), ('5', 'SCIENCE_TECH')], default='1', max_length=20),
        ),
    ]
