# Generated by Django 3.1.2 on 2020-11-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201120_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=24, verbose_name='Free Test Email')),
            ],
        ),
    ]
