# Generated by Django 3.1.2 on 2020-12-18 06:39

import army_backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_headerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollOfHonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=army_backend.utils.upload_image, verbose_name='Upload Header Picture')),
                ('choice', models.CharField(choices=[('Star of Today', 'Star of Today'), ('Evergreeen Stars', 'Evergreeen Stars')], default='Star of Today', max_length=20)),
                ('heading', models.CharField(blank=True, max_length=30, null=True)),
                ('text', models.TextField(max_length=200)),
            ],
        ),
    ]
