# Generated by Django 3.1.2 on 2020-12-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rollofhonor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=25, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('query', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
