# Generated by Django 3.1.2 on 2020-12-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_notification_videocontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='title',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
    ]
