# Generated by Django 3.1.2 on 2020-12-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_videocontent_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocontent',
            name='size',
        ),
    ]
