# Generated by Django 3.1.2 on 2020-10-09 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=24, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_student', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1)),
                ('department', models.IntegerField(choices=[(1, 'PP'), (2, 'IO')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1)),
                ('dob', models.DateField(verbose_name='DOB')),
                ('occupation', models.CharField(max_length=128)),
                ('marital_status', models.IntegerField(choices=[(1, 'Single'), (2, 'Married')], default=1)),
                ('mobile', models.IntegerField(verbose_name='Mobile Number')),
                ('address', models.TextField(verbose_name='address')),
                ('post_office', models.CharField(max_length=128)),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, to='accounts.assessor')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10, verbose_name='Test')),
                ('remark', models.CharField(max_length=96, verbose_name='Remarks')),
                ('comment', models.CharField(max_length=96, verbose_name='Comment')),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, to='accounts.assessor')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, to='accounts.student')),
            ],
        ),
    ]
