# Generated by Django 3.1.2 on 2020-10-12 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_block', models.CharField(max_length=24)),
                ('street', models.CharField(blank=True, max_length=24, null=True)),
                ('area', models.CharField(blank=True, max_length=48, null=True)),
                ('phone', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.city')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1)),
                ('dob', models.DateField(verbose_name='DOB')),
                ('occupation', models.IntegerField(choices=[(1, 'O1'), (2, 'O2'), (3, 'O3')], default=1)),
                ('marital_status', models.IntegerField(choices=[(1, 'Single'), (2, 'Married')], default=1)),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('security_question', models.IntegerField(choices=[(1, 'SQ_1'), (2, 'SQ_2'), (3, 'SQ_3')], default=1)),
                ('security_answer', models.CharField(max_length=48)),
                ('plan', models.IntegerField(choices=[(0, 'None'), (1, 'DIAMOND'), (2, 'GOLD'), (3, 'SILVER'), (4, 'INSTITUTIONAL')], default=0)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, to='assessor.assessor')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10, verbose_name='Test')),
                ('remark', models.CharField(max_length=96, verbose_name='Remarks')),
                ('comment', models.CharField(max_length=96, verbose_name='Comment')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Done')], default=2)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, to='assessor.assessor')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(verbose_name='report')),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessor.assessor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_name', models.CharField(max_length=64)),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.pincode')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.state'),
        ),
        migrations.AddField(
            model_name='address',
            name='post_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.postoffice'),
        ),
    ]
