# Generated by Django 3.1.2 on 2020-10-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamschedule',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Complete'), (3, 'Expired')], default=1),
        ),
    ]
