# Generated by Django 3.1.2 on 2020-10-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_streamschedule_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamschedule',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='streamschedule',
            name='remark',
            field=models.CharField(blank=True, max_length=96, null=True, verbose_name='Remarks'),
        ),
    ]
