# Generated by Django 3.1.2 on 2020-10-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20201024_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='images',
            field=models.ManyToManyField(blank=True, to='student.TestImages'),
        ),
    ]
