# Generated by Django 3.1.2 on 2020-10-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20201024_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='answer_display_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='question_display_time',
            field=models.IntegerField(default=0),
        ),
    ]
