# Generated by Django 3.1.2 on 2020-10-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20201024_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsubmission',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Test Answer'),
        ),
    ]
