# Generated by Django 3.1.2 on 2020-11-23 07:16

import army_backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=army_backend.utils.upload_image, verbose_name='Upload Question Image'),
        ),
    ]
