# Generated by Django 3.1.2 on 2020-12-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20201123_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Instruction')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='instructions',
            field=models.ManyToManyField(blank=True, to='student.TestInstruction'),
        ),
    ]
